baseURL = "https://www.samcalamos.com.au/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "hugo-coder"
title = "Sam Calamos"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Sam Calamos"
  colorScheme = "dark"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  #  = "Landing Page"
  info = "I work in the Clouds ☁"
  avatarURL = "images/BlueAlder_DP.png"
  avatarSize = "size-xl"
  favicon = "images/favicon/favicon.ico"
  error404 = "There is no such page."
  hideCredits = true
  customCSS = ["css/styles.css"]

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/BlueAlder"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/BlueAlder" 

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:sam.calamos@gmail.com" 

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/samuelcalamos/" 

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"